; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
 
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.cpu_freq = 240
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_DFU_ON_BOOT=0
    -D ARDUINO_USB_MANUFACTURER="Espressif"
    -D ARDUINO_USB_PRODUCT="ESP32-S3 Dev Module"
monitor_speed = 921600
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
    teemuatlut/TMCStepper@^0.7.0
    adafruit/Adafruit NeoPixel@^1.12.0
    https://github.com/me-no-dev/ESPAsyncWebServer
    https://github.com/me-no-dev/AsyncTCP
    bblanchon/ArduinoJson@^7.4.2
board_microros_distro = humble
board_microros_transport = serial
board_microros_agent = serial
lib_ldf_mode = chain+