; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@6.6.0
board = esp32-s3-devkitc-1
board_build.flash_size = 8MB
board_microros_user_meta = action.meta
framework = arduino
board_build.cpu_freq = 240
board_microros_transport = wifi
board_microros_distro = humble
board_microros_agent_ip = 172.250.250.85
board_microros_agent_port = 8888
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
	teemuatlut/TMCStepper@^0.7.0
	https://github.com/sparkfun/SparkFun_Qwiic_6DoF_LSM6DSO_Arduino_Library.git
build_flags =
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D RMW_UXRCE_TRANSPORT_CUSTOM_SERIAL_BUFFER_SIZE=1024
	-D CONFIG_FREERTOS_HZ=1000
	-D CONFIG_ESP_MAIN_TASK_STACK_SIZE=16384
	-D CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE=8192
	-D CONFIG_ESP_TIMER_TASK_STACK_SIZE=8192
lib_ldf_mode = chain+
